services:
  - type: web
    name: carb-manager-strapi
    env: node
    region: oregon
    plan: starter
    branch: master
    buildCommand: npm install && npm build
    startCommand: npm start
    healthCheckPath: /_health
    disk:
      name: strapi-uploads
      mountPath: /opt/render/project/src/public/uploads
      sizeGB: 1
    envVars:
      - key: NODE_VERSION
        value: 14.17.0
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: carb-manager-strapi-pgsql
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: APP_KEYS
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true

databases:
  - name: carb-manager-strapi-pgsql
    plan: starter